service: sspilsbury-com
provider:
  name: aws
  runtime: nodejs6.10
functions:
  api:
    handler: ./prodLambda.handler
    environment:
      NODE_ENV: production
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY